version: '3.9'

services:
  keycloak-dev:
    container_name: keycloak-hs-ddd
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLE=true
      - KC_METRICS_ENABLE=true
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-keycloak-dev
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    command: start-dev
    networks:
      - keycloak-red
    depends_on:
      - postgres-keycloak-dev
  postgres-keycloak-dev:
    container_name: postgres-keycloak-hs-ddd
    image: postgres:15-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    networks:
      - keycloak-red

  mongodb-dev:
    image: 'mongo:latest'
    container_name: 'mongodb-hs-ddd'
    environment:
      - 'MONGO_INITDB_DATABASE=hs_nourishment'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '27017:27017'
    networks:
      - 'mongodb-red'

networks:
  keycloak-red:
    driver: bridge
  mongodb-red:
    driver: bridge




